package edu.tamu.ctv.entity;
// Generated Sep 7, 2015 3:40:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Columntypes generated by hbm2java
 */
public class Columntypes implements java.io.Serializable
{

	private int id;
	private Columntypes columntypes;
	private Projects projects;
	private String code;
	private String name;
	private String notes;
	private Date registereddt;
	private Date lastvisitdt;
	private Set columnheaderses = new HashSet(0);
	private Set columntypeses = new HashSet(0);

	public Columntypes()
	{
	}

	public Columntypes(int id, Projects projects, String code, String name, Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.projects = projects;
		this.code = code;
		this.name = name;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public Columntypes(int id, Columntypes columntypes, Projects projects, String code, String name, String notes, Date registereddt, Date lastvisitdt, Set columnheaderses, Set columntypeses)
	{
		this.id = id;
		this.columntypes = columntypes;
		this.projects = projects;
		this.code = code;
		this.name = name;
		this.notes = notes;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
		this.columnheaderses = columnheaderses;
		this.columntypeses = columntypeses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}
	
	public Columntypes getColumntypes()
	{
		return this.columntypes;
	}

	public void setColumntypes(Columntypes columntypes)
	{
		this.columntypes = columntypes;
	}

	public Projects getProjects()
	{
		return this.projects;
	}

	public void setProjects(Projects projects)
	{
		this.projects = projects;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Date getRegistereddt()
	{
		return this.registereddt;
	}

	public void setRegistereddt(Date registereddt)
	{
		this.registereddt = registereddt;
	}

	public Date getLastvisitdt()
	{
		return this.lastvisitdt;
	}

	public void setLastvisitdt(Date lastvisitdt)
	{
		this.lastvisitdt = lastvisitdt;
	}

	public Set getColumnheaderses()
	{
		return this.columnheaderses;
	}

	public void setColumnheaderses(Set columnheaderses)
	{
		this.columnheaderses = columnheaderses;
	}

	public Set getColumntypeses()
	{
		return this.columntypeses;
	}

	public void setColumntypeses(Set columntypeses)
	{
		this.columntypeses = columntypeses;
	}
}
