package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Components generated by hbm2java
 */
public class Components implements java.io.Serializable
{

	private Long id;
	private Columnheaders columnheaders;
	private Projects projects;
	private Units units;
	private Users users;
	private String code;
	private String name;
	private String notes;
	private Integer color;
	private Date updateddt;
	private Set<Results> resultses = new HashSet<Results>(0);

	public Components()
	{
	}

	public Components(Long id, Projects projects, Units units, Users users, String code, String name, Date updateddt)
	{
		this.id = id;
		this.projects = projects;
		this.units = units;
		this.users = users;
		this.code = code;
		this.name = name;
		this.updateddt = updateddt;
	}

	public Components(Long id, Columnheaders columnheaders, Projects projects, Units units, Users users, String code, String name, String notes, Integer color, Date updateddt, Set<Results> resultses)
	{
		this.id = id;
		this.columnheaders = columnheaders;
		this.projects = projects;
		this.units = units;
		this.users = users;
		this.code = code;
		this.name = name;
		this.notes = notes;
		this.color = color;
		this.updateddt = updateddt;
		this.resultses = resultses;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}
	
	public Columnheaders getColumnheaders()
	{
		return this.columnheaders;
	}

	public void setColumnheaders(Columnheaders columnheaders)
	{
		this.columnheaders = columnheaders;
	}
	
	public Projects getProjects()
	{
		return this.projects;
	}

	public void setProjects(Projects projects)
	{
		this.projects = projects;
	}

	public Units getUnits()
	{
		return this.units;
	}

	public void setUnits(Units units)
	{
		this.units = units;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Integer getColor()
	{
		return this.color;
	}

	public void setColor(Integer color)
	{
		this.color = color;
	}

	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

	public Set<Results> getResultses()
	{
		return this.resultses;
	}

	public void setResultses(Set<Results> resultses)
	{
		this.resultses = resultses;
	}
}
