package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Notes generated by hbm2java
 */
public class Notes implements Serializable
{

	private Long id;
	private Users users;
	private String code;
	private String note;
	private int ownerId;
	private Serializable ownertype;
	private boolean visible;
	private Date updateddt;

	public Notes()
	{
	}

	public Notes(Long id, Users users, String code, int ownerId, Serializable ownertype, boolean visible, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.ownerId = ownerId;
		this.ownertype = ownertype;
		this.visible = visible;
		this.updateddt = updateddt;
	}

	public Notes(Long id, Users users, String code, String note, int ownerId, Serializable ownertype, boolean visible, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.note = note;
		this.ownerId = ownerId;
		this.ownertype = ownertype;
		this.visible = visible;
		this.updateddt = updateddt;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getNote()
	{
		return this.note;
	}

	public void setNote(String note)
	{
		this.note = note;
	}

	public int getOwnerId()
	{
		return this.ownerId;
	}

	public void setOwnerId(int ownerId)
	{
		this.ownerId = ownerId;
	}

	public Serializable getOwnertype()
	{
		return this.ownertype;
	}

	public void setOwnertype(Serializable ownertype)
	{
		this.ownertype = ownertype;
	}

	public boolean isVisible()
	{
		return this.visible;
	}

	public void setVisible(boolean visible)
	{
		this.visible = visible;
	}

	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

}
