package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable
{

	private Long id;
	private Rowheaders rowheaders;
	private Long orderId;

	public Orders()
	{
	}

	public Orders(Long id, Rowheaders rowheaders, Long orderId)
	{
		this.id = id;
		this.rowheaders = rowheaders;
		this.orderId = orderId;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Rowheaders getRowheaders()
	{
		return this.rowheaders;
	}

	public void setRowheaders(Rowheaders rowheaders)
	{
		this.rowheaders = rowheaders;
	}

	public Long getOrderId()
	{
		return this.orderId;
	}

	public void setOrderId(Long orderId)
	{
		this.orderId = orderId;
	}

}
