package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Projectmembers generated by hbm2java
 */
public class Projectmembers implements java.io.Serializable
{

	private int id;
	private Projects projects;
	private Userroles userroles;
	private Users users;
	private String notes;
	private Date registereddt;
	private Date lastvisitdt;

	public Projectmembers()
	{
	}

	public Projectmembers(int id, Projects projects, Userroles userroles, Users users, Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.projects = projects;
		this.userroles = userroles;
		this.users = users;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public Projectmembers(int id, Projects projects, Userroles userroles, Users users, String notes, Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.projects = projects;
		this.userroles = userroles;
		this.users = users;
		this.notes = notes;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Projects getProjects()
	{
		return this.projects;
	}

	public void setProjects(Projects projects)
	{
		this.projects = projects;
	}

	public Userroles getUserroles()
	{
		return this.userroles;
	}

	public void setUserroles(Userroles userroles)
	{
		this.userroles = userroles;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Date getRegistereddt()
	{
		return this.registereddt;
	}

	public void setRegistereddt(Date registereddt)
	{
		this.registereddt = registereddt;
	}

	public Date getLastvisitdt()
	{
		return this.lastvisitdt;
	}

	public void setLastvisitdt(Date lastvisitdt)
	{
		this.lastvisitdt = lastvisitdt;
	}

}
