package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rowheaders generated by hbm2java
 */
public class Rowheaders implements java.io.Serializable
{

	private Long id;
	private Rowtypes rowtypes;
	private String code;
	private String name;
	private String notes;
	private Integer color;
	private Date registereddt;
	private Date lastvisitdt;
	private Set orderses = new HashSet(0);

	public Rowheaders()
	{
	}

	public Rowheaders(Long id, Rowtypes rowtypes, String code, String name, Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.rowtypes = rowtypes;
		this.code = code;
		this.name = name;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public Rowheaders(Long id, Rowtypes rowtypes, String code, String name, String notes, Integer color, Date registereddt, Date lastvisitdt, Set orderses)
	{
		this.id = id;
		this.rowtypes = rowtypes;
		this.code = code;
		this.name = name;
		this.notes = notes;
		this.color = color;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
		this.orderses = orderses;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Rowtypes getRowtypes()
	{
		return this.rowtypes;
	}

	public void setRowtypes(Rowtypes rowtypes)
	{
		this.rowtypes = rowtypes;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}
	
	public Integer getColor()
	{
		return this.color;
	}

	public void setColor(Integer color)
	{
		this.color = color;
	}

	public Date getRegistereddt()
	{
		return this.registereddt;
	}

	public void setRegistereddt(Date registereddt)
	{
		this.registereddt = registereddt;
	}

	public Date getLastvisitdt()
	{
		return this.lastvisitdt;
	}

	public void setLastvisitdt(Date lastvisitdt)
	{
		this.lastvisitdt = lastvisitdt;
	}

	public Set getOrderses()
	{
		return this.orderses;
	}

	public void setOrderses(Set orderses)
	{
		this.orderses = orderses;
	}
}
