package edu.tamu.ctv.entity;
// Generated Sep 7, 2015 3:40:07 PM by Hibernate Tools 4.3.1.Final

/**
 * Columnheaders generated by hbm2java
 */
public class Sequences implements java.io.Serializable
{
	private Long id;
	public Sequences()
	{
	}

	public Sequences(Long id)
	{
		this.id = id;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

}
