package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Units units;
	private Users users;
	private String code;
	private String name;
	private BigDecimal volumeof;
	private Date updateddt;
	private Set<Units> unitses = new HashSet<Units>(0);
	private Set<Components> componentses = new HashSet<Components>(0);

	public Units()
	{
	}

	public Units(Long id, Users users, String code, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.updateddt = updateddt;
	}

	public Units(Long id, Units units, Users users, String code, String name, BigDecimal volumeof, Date updateddt, Set<Units> unitses, Set<Components> componentses)
	{
		this.id = id;
		this.units = units;
		this.users = users;
		this.code = code;
		this.name = name;
		this.volumeof = volumeof;
		this.updateddt = updateddt;
		this.unitses = unitses;
		this.componentses = componentses;
	}

	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Units getUnits()
	{
		return units;
	}

	public void setUnits(Units units)
	{
		this.units = units;
	}

	public Users getUsers()
	{
		return users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public String getCode()
	{
		return code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getVolumeof()
	{
		return volumeof;
	}

	public void setVolumeof(BigDecimal volumeof)
	{
		this.volumeof = volumeof;
	}

	public Date getUpdateddt()
	{
		return updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

	public Set<Units> getUnitses()
	{
		return unitses;
	}

	public void setUnitses(Set<Units> unitses)
	{
		this.unitses = unitses;
	}

	public Set<Components> getComponentses()
	{
		return componentses;
	}

	public void setComponentses(Set<Components> componentses)
	{
		this.componentses = componentses;
	}


}
