package edu.tamu.ctv.entity;
// Generated Sep 6, 2015 12:46:57 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements Serializable
{

	private int id;
	private String login;
	private String password;
	private String firstname;
	private String lastname;
	private String email;
	private String phone;
	private String address1;
	private String address2;
	private String country;
	private String state;
	private String zip;
	private String sex;
	private String organization;
	private String organaddress;
	private byte[] photo;
	private String notes;
	private Date registereddt;
	private Date lastvisitdt;
	private Set resultses = new HashSet(0);
	private Set importinfos = new HashSet(0);
	private Set componentses = new HashSet(0);
	private Set resultshistories = new HashSet(0);
	private Set viewtemplatesesForUpdatedby = new HashSet(0);
	private Set viewtemplatesesForUserId = new HashSet(0);
	private Set noteses = new HashSet(0);
	private Set projectmemberses = new HashSet(0);
	private Set unitses = new HashSet(0);
	private Set projectses = new HashSet(0);

	public Users()
	{
	}

	public Users(int id, String login, String password, String firstname, String lastname, String email, String phone, String address1, String country, String state, String zip, String sex,
			Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.login = login;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.address1 = address1;
		this.country = country;
		this.state = state;
		this.zip = zip;
		this.sex = sex;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public Users(int id, String login, String password, String firstname, String lastname, String email, String phone, String address1, String address2, String country, String state, String zip,
			String sex, String organization, String organaddress, byte[] photo, String notes, Date registereddt, Date lastvisitdt, Set resultses, Set importinfos, Set componentses, Set resultshistories,
			Set viewtemplatesesForUpdatedby, Set viewtemplatesesForUserId, Set noteses, Set projectmemberses, Set unitses, Set projectses)
	{
		this.id = id;
		this.login = login;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.address1 = address1;
		this.address2 = address2;
		this.country = country;
		this.state = state;
		this.zip = zip;
		this.sex = sex;
		this.organization = organization;
		this.organaddress = organaddress;
		this.photo = photo;
		this.notes = notes;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
		this.resultses = resultses;
		this.importinfos = importinfos;
		this.componentses = componentses;
		this.resultshistories = resultshistories;
		this.viewtemplatesesForUpdatedby = viewtemplatesesForUpdatedby;
		this.viewtemplatesesForUserId = viewtemplatesesForUserId;
		this.noteses = noteses;
		this.projectmemberses = projectmemberses;
		this.unitses = unitses;
		this.projectses = projectses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getLogin()
	{
		return this.login;
	}

	public void setLogin(String login)
	{
		this.login = login;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getFirstname()
	{
		return this.firstname;
	}

	public void setFirstname(String firstname)
	{
		this.firstname = firstname;
	}

	public String getLastname()
	{
		return this.lastname;
	}

	public void setLastname(String lastname)
	{
		this.lastname = lastname;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getPhone()
	{
		return this.phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getAddress1()
	{
		return this.address1;
	}

	public void setAddress1(String address1)
	{
		this.address1 = address1;
	}

	public String getAddress2()
	{
		return this.address2;
	}

	public void setAddress2(String address2)
	{
		this.address2 = address2;
	}

	public String getCountry()
	{
		return this.country;
	}

	public void setCountry(String country)
	{
		this.country = country;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public String getZip()
	{
		return this.zip;
	}

	public void setZip(String zip)
	{
		this.zip = zip;
	}

	public String getSex()
	{
		return this.sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(String organization)
	{
		this.organization = organization;
	}

	public String getOrganaddress()
	{
		return this.organaddress;
	}

	public void setOrganaddress(String organaddress)
	{
		this.organaddress = organaddress;
	}

	public byte[] getPhoto()
	{
		return this.photo;
	}

	public void setPhoto(byte[] photo)
	{
		this.photo = photo;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Date getRegistereddt()
	{
		return this.registereddt;
	}

	public void setRegistereddt(Date registereddt)
	{
		this.registereddt = registereddt;
	}

	public Date getLastvisitdt()
	{
		return this.lastvisitdt;
	}

	public void setLastvisitdt(Date lastvisitdt)
	{
		this.lastvisitdt = lastvisitdt;
	}

	public Set getResultses()
	{
		return this.resultses;
	}

	public void setResultses(Set resultses)
	{
		this.resultses = resultses;
	}

	public Set getImportinfos()
	{
		return this.importinfos;
	}

	public void setImportinfos(Set importinfos)
	{
		this.importinfos = importinfos;
	}

	public Set getComponentses()
	{
		return this.componentses;
	}

	public void setComponentses(Set componentses)
	{
		this.componentses = componentses;
	}

	public Set getResultshistories()
	{
		return this.resultshistories;
	}

	public void setResultshistories(Set resultshistories)
	{
		this.resultshistories = resultshistories;
	}

	public Set getViewtemplatesesForUpdatedby()
	{
		return this.viewtemplatesesForUpdatedby;
	}

	public void setViewtemplatesesForUpdatedby(Set viewtemplatesesForUpdatedby)
	{
		this.viewtemplatesesForUpdatedby = viewtemplatesesForUpdatedby;
	}

	public Set getViewtemplatesesForUserId()
	{
		return this.viewtemplatesesForUserId;
	}

	public void setViewtemplatesesForUserId(Set viewtemplatesesForUserId)
	{
		this.viewtemplatesesForUserId = viewtemplatesesForUserId;
	}

	public Set getNoteses()
	{
		return this.noteses;
	}

	public void setNoteses(Set noteses)
	{
		this.noteses = noteses;
	}

	public Set getProjectmemberses()
	{
		return this.projectmemberses;
	}

	public void setProjectmemberses(Set projectmemberses)
	{
		this.projectmemberses = projectmemberses;
	}

	public Set getUnitses()
	{
		return this.unitses;
	}

	public void setUnitses(Set unitses)
	{
		this.unitses = unitses;
	}

	public Set getProjectses()
	{
		return this.projectses;
	}

	public void setProjectses(Set projectses)
	{
		this.projectses = projectses;
	}

}
