package edu.tamu.ctv.entity;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Viewtemplates generated by hbm2java
 */
public class Viewtemplates implements Serializable
{

	private Long id;
	private Users usersByUpdatedby;
	private Users usersByUserId;
	private String code;
	private String name;
	private Serializable objectxml;
	private Date updateddt;

	public Viewtemplates()
	{
	}

	public Viewtemplates(Long id, Users usersByUpdatedby, Users usersByUserId, String code, String name, Date updateddt)
	{
		this.id = id;
		this.usersByUpdatedby = usersByUpdatedby;
		this.usersByUserId = usersByUserId;
		this.code = code;
		this.name = name;
		this.updateddt = updateddt;
	}

	public Viewtemplates(Long id, Users usersByUpdatedby, Users usersByUserId, String code, String name, Serializable objectxml, Date updateddt)
	{
		this.id = id;
		this.usersByUpdatedby = usersByUpdatedby;
		this.usersByUserId = usersByUserId;
		this.code = code;
		this.name = name;
		this.objectxml = objectxml;
		this.updateddt = updateddt;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Users getUsersByUpdatedby()
	{
		return this.usersByUpdatedby;
	}

	public void setUsersByUpdatedby(Users usersByUpdatedby)
	{
		this.usersByUpdatedby = usersByUpdatedby;
	}

	public Users getUsersByUserId()
	{
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId)
	{
		this.usersByUserId = usersByUserId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Serializable getObjectxml()
	{
		return this.objectxml;
	}

	public void setObjectxml(Serializable objectxml)
	{
		this.objectxml = objectxml;
	}

	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

}
